version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/api.pwa.nicolas-schneider.fr/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/api.pwa.nicolas-schneider.fr/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - prod_postgres:/var/lib/postgresql/data

  app:
    build: .
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST_PROD}
      - SECRET_KEY=${SECRET_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_MAILTO=${VAPID_MAILTO}
    depends_on:
      - postgres

volumes:
  prod_postgres: